// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace device_kit_lib {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class DeviceKitHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class UiAction {
  kPress = 0,
  kFocus = 1,
  kSetValue = 2,
  kScrollForward = 3,
  kScrollBackward = 4
};


// Generated class from Pigeon that represents data sent in messages.
class DriverConfig {
 public:
  // Constructs an object setting all fields.
  explicit DriverConfig(
    const std::string& session_id,
    bool enable_logs);

  const std::string& session_id() const;
  void set_session_id(std::string_view value_arg);

  bool enable_logs() const;
  void set_enable_logs(bool value_arg);

  bool operator==(const DriverConfig& other) const;
  bool operator!=(const DriverConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const DriverConfig& obj);
 private:
  static DriverConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string session_id_;
  bool enable_logs_;
};


// Generated class from Pigeon that represents data sent in messages.
class DeviceInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DeviceInfo(
    const std::string& platform,
    bool physical_device);

  // Constructs an object setting all fields.
  explicit DeviceInfo(
    const std::string& platform,
    const std::string* os_version,
    const std::string* model,
    const std::string* device_name,
    bool physical_device);

  const std::string& platform() const;
  void set_platform(std::string_view value_arg);

  const std::string* os_version() const;
  void set_os_version(const std::string_view* value_arg);
  void set_os_version(std::string_view value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const std::string* device_name() const;
  void set_device_name(const std::string_view* value_arg);
  void set_device_name(std::string_view value_arg);

  bool physical_device() const;
  void set_physical_device(bool value_arg);

  bool operator==(const DeviceInfo& other) const;
  bool operator!=(const DeviceInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const DeviceInfo& obj);
 private:
  static DeviceInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string platform_;
  std::optional<std::string> os_version_;
  std::optional<std::string> model_;
  std::optional<std::string> device_name_;
  bool physical_device_;
};


// Generated class from Pigeon that represents data sent in messages.
class RectData {
 public:
  // Constructs an object setting all fields.
  explicit RectData(
    double x,
    double y,
    double width,
    double height);

  double x() const;
  void set_x(double value_arg);

  double y() const;
  void set_y(double value_arg);

  double width() const;
  void set_width(double value_arg);

  double height() const;
  void set_height(double value_arg);

  bool operator==(const RectData& other) const;
  bool operator!=(const RectData& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const RectData& obj);
 private:
  static RectData FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class UiNode;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  double x_;
  double y_;
  double width_;
  double height_;
};


// Generated class from Pigeon that represents data sent in messages.
class UiNode {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit UiNode(
    const std::string& node_id,
    const ::flutter::EncodableList& child_node_ids,
    const std::string& role,
    const RectData& bounds,
    bool enabled,
    bool clickable,
    bool editable,
    bool focused,
    bool selected,
    bool checked,
    bool scrollable);

  // Constructs an object setting all fields.
  explicit UiNode(
    const std::string& node_id,
    const std::string* parent_node_id,
    const ::flutter::EncodableList& child_node_ids,
    const std::string* automation_id,
    const std::string* text,
    const std::string* label,
    const std::string* value,
    const std::string& role,
    const RectData& bounds,
    bool enabled,
    bool clickable,
    bool editable,
    bool focused,
    bool selected,
    bool checked,
    bool scrollable);

  ~UiNode() = default;
  UiNode(const UiNode& other);
  UiNode& operator=(const UiNode& other);
  UiNode(UiNode&& other) = default;
  UiNode& operator=(UiNode&& other) noexcept = default;
  const std::string& node_id() const;
  void set_node_id(std::string_view value_arg);

  const std::string* parent_node_id() const;
  void set_parent_node_id(const std::string_view* value_arg);
  void set_parent_node_id(std::string_view value_arg);

  const ::flutter::EncodableList& child_node_ids() const;
  void set_child_node_ids(const ::flutter::EncodableList& value_arg);

  const std::string* automation_id() const;
  void set_automation_id(const std::string_view* value_arg);
  void set_automation_id(std::string_view value_arg);

  const std::string* text() const;
  void set_text(const std::string_view* value_arg);
  void set_text(std::string_view value_arg);

  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  const std::string* value() const;
  void set_value(const std::string_view* value_arg);
  void set_value(std::string_view value_arg);

  const std::string& role() const;
  void set_role(std::string_view value_arg);

  const RectData& bounds() const;
  void set_bounds(const RectData& value_arg);

  bool enabled() const;
  void set_enabled(bool value_arg);

  bool clickable() const;
  void set_clickable(bool value_arg);

  bool editable() const;
  void set_editable(bool value_arg);

  bool focused() const;
  void set_focused(bool value_arg);

  bool selected() const;
  void set_selected(bool value_arg);

  bool checked() const;
  void set_checked(bool value_arg);

  bool scrollable() const;
  void set_scrollable(bool value_arg);

  bool operator==(const UiNode& other) const;
  bool operator!=(const UiNode& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const UiNode& obj);
 private:
  static UiNode FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string node_id_;
  std::optional<std::string> parent_node_id_;
  ::flutter::EncodableList child_node_ids_;
  std::optional<std::string> automation_id_;
  std::optional<std::string> text_;
  std::optional<std::string> label_;
  std::optional<std::string> value_;
  std::string role_;
  std::unique_ptr<RectData> bounds_;
  bool enabled_;
  bool clickable_;
  bool editable_;
  bool focused_;
  bool selected_;
  bool checked_;
  bool scrollable_;
};


// Generated class from Pigeon that represents data sent in messages.
class UiSnapshot {
 public:
  // Constructs an object setting all fields.
  explicit UiSnapshot(
    int64_t generation,
    const ::flutter::EncodableList& nodes);

  int64_t generation() const;
  void set_generation(int64_t value_arg);

  const ::flutter::EncodableList& nodes() const;
  void set_nodes(const ::flutter::EncodableList& value_arg);

  bool operator==(const UiSnapshot& other) const;
  bool operator!=(const UiSnapshot& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const UiSnapshot& obj);
 private:
  static UiSnapshot FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t generation_;
  ::flutter::EncodableList nodes_;
};


// Generated class from Pigeon that represents data sent in messages.
class ActionResult {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ActionResult(
    bool success,
    bool ui_changed);

  // Constructs an object setting all fields.
  explicit ActionResult(
    bool success,
    const std::string* message,
    bool ui_changed);

  bool success() const;
  void set_success(bool value_arg);

  const std::string* message() const;
  void set_message(const std::string_view* value_arg);
  void set_message(std::string_view value_arg);

  bool ui_changed() const;
  void set_ui_changed(bool value_arg);

  bool operator==(const ActionResult& other) const;
  bool operator!=(const ActionResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ActionResult& obj);
 private:
  static ActionResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class DeviceKitHostApi;
  friend class PigeonInternalCodecSerializer;
  bool success_;
  std::optional<std::string> message_;
  bool ui_changed_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class DeviceKitHostApi {
 public:
  DeviceKitHostApi(const DeviceKitHostApi&) = delete;
  DeviceKitHostApi& operator=(const DeviceKitHostApi&) = delete;
  virtual ~DeviceKitHostApi() {}
  virtual std::optional<FlutterError> Initialize(const DriverConfig& config) = 0;
  virtual std::optional<FlutterError> Dispose() = 0;
  virtual ErrorOr<DeviceInfo> GetDeviceInfo() = 0;
  virtual ErrorOr<ActionResult> OpenAccessibilitySettings() = 0;
  virtual ErrorOr<ActionResult> LaunchApp(const std::string& package_name) = 0;
  virtual ErrorOr<UiSnapshot> DumpUi() = 0;
  virtual ErrorOr<ActionResult> PerformElementAction(
    const std::string& node_id,
    int64_t generation,
    const UiAction& action,
    const std::string* value) = 0;
  virtual ErrorOr<ActionResult> Tap(
    double x,
    double y) = 0;
  virtual ErrorOr<ActionResult> Swipe(
    double from_x,
    double from_y,
    double to_x,
    double to_y,
    int64_t duration_ms) = 0;
  virtual ErrorOr<ActionResult> TypeText(const std::string& text) = 0;
  virtual ErrorOr<ActionResult> PressBack() = 0;
  virtual ErrorOr<ActionResult> PressHome() = 0;
  virtual ErrorOr<std::vector<uint8_t>> Screenshot() = 0;
  virtual ErrorOr<ActionResult> RequestScreenCapture() = 0;
  virtual ErrorOr<std::optional<std::string>> GetClipboard() = 0;
  virtual ErrorOr<ActionResult> SetClipboard(const std::string& text) = 0;

  // The codec used by DeviceKitHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `DeviceKitHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    DeviceKitHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    DeviceKitHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  DeviceKitHostApi() = default;
};
}  // namespace device_kit_lib
#endif  // PIGEON_MESSAGES_G_H_
