// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace device_kit_lib {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// DriverConfig

DriverConfig::DriverConfig(
  const std::string& session_id,
  bool enable_logs)
 : session_id_(session_id),
    enable_logs_(enable_logs) {}

const std::string& DriverConfig::session_id() const {
  return session_id_;
}

void DriverConfig::set_session_id(std::string_view value_arg) {
  session_id_ = value_arg;
}


bool DriverConfig::enable_logs() const {
  return enable_logs_;
}

void DriverConfig::set_enable_logs(bool value_arg) {
  enable_logs_ = value_arg;
}


EncodableList DriverConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(session_id_));
  list.push_back(EncodableValue(enable_logs_));
  return list;
}

DriverConfig DriverConfig::FromEncodableList(const EncodableList& list) {
  DriverConfig decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[1]));
  return decoded;
}

bool DriverConfig::operator==(const DriverConfig& other) const {
  return PigeonInternalDeepEquals(session_id_, other.session_id_) && PigeonInternalDeepEquals(enable_logs_, other.enable_logs_);
}

bool DriverConfig::operator!=(const DriverConfig& other) const {
  return !(*this == other);
}

size_t DriverConfig::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(session_id_);
  result = result * 31 + PigeonInternalDeepHash(enable_logs_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DriverConfig& obj) {
  os << "DriverConfig(";
  os << "session_id: ";
  os << PigeonInternalToString(obj.session_id_);
  os << ", enable_logs: ";
  os << PigeonInternalToString(obj.enable_logs_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DriverConfig& v) {
  return v.Hash();
}

// DeviceInfo

DeviceInfo::DeviceInfo(
  const std::string& platform,
  bool physical_device)
 : platform_(platform),
    physical_device_(physical_device) {}

DeviceInfo::DeviceInfo(
  const std::string& platform,
  const std::string* os_version,
  const std::string* model,
  const std::string* device_name,
  bool physical_device)
 : platform_(platform),
    os_version_(os_version ? std::optional<std::string>(*os_version) : std::nullopt),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    device_name_(device_name ? std::optional<std::string>(*device_name) : std::nullopt),
    physical_device_(physical_device) {}

const std::string& DeviceInfo::platform() const {
  return platform_;
}

void DeviceInfo::set_platform(std::string_view value_arg) {
  platform_ = value_arg;
}


const std::string* DeviceInfo::os_version() const {
  return os_version_ ? &(*os_version_) : nullptr;
}

void DeviceInfo::set_os_version(const std::string_view* value_arg) {
  os_version_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DeviceInfo::set_os_version(std::string_view value_arg) {
  os_version_ = value_arg;
}


const std::string* DeviceInfo::model() const {
  return model_ ? &(*model_) : nullptr;
}

void DeviceInfo::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DeviceInfo::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const std::string* DeviceInfo::device_name() const {
  return device_name_ ? &(*device_name_) : nullptr;
}

void DeviceInfo::set_device_name(const std::string_view* value_arg) {
  device_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DeviceInfo::set_device_name(std::string_view value_arg) {
  device_name_ = value_arg;
}


bool DeviceInfo::physical_device() const {
  return physical_device_;
}

void DeviceInfo::set_physical_device(bool value_arg) {
  physical_device_ = value_arg;
}


EncodableList DeviceInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(platform_));
  list.push_back(os_version_ ? EncodableValue(*os_version_) : EncodableValue());
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(device_name_ ? EncodableValue(*device_name_) : EncodableValue());
  list.push_back(EncodableValue(physical_device_));
  return list;
}

DeviceInfo DeviceInfo::FromEncodableList(const EncodableList& list) {
  DeviceInfo decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[4]));
  auto& encodable_os_version = list[1];
  if (!encodable_os_version.IsNull()) {
    decoded.set_os_version(std::get<std::string>(encodable_os_version));
  }
  auto& encodable_model = list[2];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_device_name = list[3];
  if (!encodable_device_name.IsNull()) {
    decoded.set_device_name(std::get<std::string>(encodable_device_name));
  }
  return decoded;
}

bool DeviceInfo::operator==(const DeviceInfo& other) const {
  return PigeonInternalDeepEquals(platform_, other.platform_) && PigeonInternalDeepEquals(os_version_, other.os_version_) && PigeonInternalDeepEquals(model_, other.model_) && PigeonInternalDeepEquals(device_name_, other.device_name_) && PigeonInternalDeepEquals(physical_device_, other.physical_device_);
}

bool DeviceInfo::operator!=(const DeviceInfo& other) const {
  return !(*this == other);
}

size_t DeviceInfo::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(platform_);
  result = result * 31 + PigeonInternalDeepHash(os_version_);
  result = result * 31 + PigeonInternalDeepHash(model_);
  result = result * 31 + PigeonInternalDeepHash(device_name_);
  result = result * 31 + PigeonInternalDeepHash(physical_device_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DeviceInfo& obj) {
  os << "DeviceInfo(";
  os << "platform: ";
  os << PigeonInternalToString(obj.platform_);
  os << ", os_version: ";
  if (obj.os_version_) {
    os << PigeonInternalToString(*obj.os_version_);
  }
  else {
    os << "null";
  }
  os << ", model: ";
  if (obj.model_) {
    os << PigeonInternalToString(*obj.model_);
  }
  else {
    os << "null";
  }
  os << ", device_name: ";
  if (obj.device_name_) {
    os << PigeonInternalToString(*obj.device_name_);
  }
  else {
    os << "null";
  }
  os << ", physical_device: ";
  os << PigeonInternalToString(obj.physical_device_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DeviceInfo& v) {
  return v.Hash();
}

// RectData

RectData::RectData(
  double x,
  double y,
  double width,
  double height)
 : x_(x),
    y_(y),
    width_(width),
    height_(height) {}

double RectData::x() const {
  return x_;
}

void RectData::set_x(double value_arg) {
  x_ = value_arg;
}


double RectData::y() const {
  return y_;
}

void RectData::set_y(double value_arg) {
  y_ = value_arg;
}


double RectData::width() const {
  return width_;
}

void RectData::set_width(double value_arg) {
  width_ = value_arg;
}


double RectData::height() const {
  return height_;
}

void RectData::set_height(double value_arg) {
  height_ = value_arg;
}


EncodableList RectData::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(x_));
  list.push_back(EncodableValue(y_));
  list.push_back(EncodableValue(width_));
  list.push_back(EncodableValue(height_));
  return list;
}

RectData RectData::FromEncodableList(const EncodableList& list) {
  RectData decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]),
    std::get<double>(list[3]));
  return decoded;
}

bool RectData::operator==(const RectData& other) const {
  return PigeonInternalDeepEquals(x_, other.x_) && PigeonInternalDeepEquals(y_, other.y_) && PigeonInternalDeepEquals(width_, other.width_) && PigeonInternalDeepEquals(height_, other.height_);
}

bool RectData::operator!=(const RectData& other) const {
  return !(*this == other);
}

size_t RectData::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(x_);
  result = result * 31 + PigeonInternalDeepHash(y_);
  result = result * 31 + PigeonInternalDeepHash(width_);
  result = result * 31 + PigeonInternalDeepHash(height_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const RectData& obj) {
  os << "RectData(";
  os << "x: ";
  os << PigeonInternalToString(obj.x_);
  os << ", y: ";
  os << PigeonInternalToString(obj.y_);
  os << ", width: ";
  os << PigeonInternalToString(obj.width_);
  os << ", height: ";
  os << PigeonInternalToString(obj.height_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const RectData& v) {
  return v.Hash();
}

// UiNode

UiNode::UiNode(
  const std::string& node_id,
  const EncodableList& child_node_ids,
  const std::string& role,
  const RectData& bounds,
  bool enabled,
  bool clickable,
  bool editable,
  bool focused,
  bool selected,
  bool checked,
  bool scrollable)
 : node_id_(node_id),
    child_node_ids_(child_node_ids),
    role_(role),
    bounds_(std::make_unique<RectData>(bounds)),
    enabled_(enabled),
    clickable_(clickable),
    editable_(editable),
    focused_(focused),
    selected_(selected),
    checked_(checked),
    scrollable_(scrollable) {}

UiNode::UiNode(
  const std::string& node_id,
  const std::string* parent_node_id,
  const EncodableList& child_node_ids,
  const std::string* automation_id,
  const std::string* text,
  const std::string* label,
  const std::string* value,
  const std::string& role,
  const RectData& bounds,
  bool enabled,
  bool clickable,
  bool editable,
  bool focused,
  bool selected,
  bool checked,
  bool scrollable)
 : node_id_(node_id),
    parent_node_id_(parent_node_id ? std::optional<std::string>(*parent_node_id) : std::nullopt),
    child_node_ids_(child_node_ids),
    automation_id_(automation_id ? std::optional<std::string>(*automation_id) : std::nullopt),
    text_(text ? std::optional<std::string>(*text) : std::nullopt),
    label_(label ? std::optional<std::string>(*label) : std::nullopt),
    value_(value ? std::optional<std::string>(*value) : std::nullopt),
    role_(role),
    bounds_(std::make_unique<RectData>(bounds)),
    enabled_(enabled),
    clickable_(clickable),
    editable_(editable),
    focused_(focused),
    selected_(selected),
    checked_(checked),
    scrollable_(scrollable) {}

UiNode::UiNode(const UiNode& other)
 : node_id_(other.node_id_),
    parent_node_id_(other.parent_node_id_ ? std::optional<std::string>(*other.parent_node_id_) : std::nullopt),
    child_node_ids_(other.child_node_ids_),
    automation_id_(other.automation_id_ ? std::optional<std::string>(*other.automation_id_) : std::nullopt),
    text_(other.text_ ? std::optional<std::string>(*other.text_) : std::nullopt),
    label_(other.label_ ? std::optional<std::string>(*other.label_) : std::nullopt),
    value_(other.value_ ? std::optional<std::string>(*other.value_) : std::nullopt),
    role_(other.role_),
    bounds_(std::make_unique<RectData>(*other.bounds_)),
    enabled_(other.enabled_),
    clickable_(other.clickable_),
    editable_(other.editable_),
    focused_(other.focused_),
    selected_(other.selected_),
    checked_(other.checked_),
    scrollable_(other.scrollable_) {}

UiNode& UiNode::operator=(const UiNode& other) {
  node_id_ = other.node_id_;
  parent_node_id_ = other.parent_node_id_;
  child_node_ids_ = other.child_node_ids_;
  automation_id_ = other.automation_id_;
  text_ = other.text_;
  label_ = other.label_;
  value_ = other.value_;
  role_ = other.role_;
  bounds_ = std::make_unique<RectData>(*other.bounds_);
  enabled_ = other.enabled_;
  clickable_ = other.clickable_;
  editable_ = other.editable_;
  focused_ = other.focused_;
  selected_ = other.selected_;
  checked_ = other.checked_;
  scrollable_ = other.scrollable_;
  return *this;
}

const std::string& UiNode::node_id() const {
  return node_id_;
}

void UiNode::set_node_id(std::string_view value_arg) {
  node_id_ = value_arg;
}


const std::string* UiNode::parent_node_id() const {
  return parent_node_id_ ? &(*parent_node_id_) : nullptr;
}

void UiNode::set_parent_node_id(const std::string_view* value_arg) {
  parent_node_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UiNode::set_parent_node_id(std::string_view value_arg) {
  parent_node_id_ = value_arg;
}


const EncodableList& UiNode::child_node_ids() const {
  return child_node_ids_;
}

void UiNode::set_child_node_ids(const EncodableList& value_arg) {
  child_node_ids_ = value_arg;
}


const std::string* UiNode::automation_id() const {
  return automation_id_ ? &(*automation_id_) : nullptr;
}

void UiNode::set_automation_id(const std::string_view* value_arg) {
  automation_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UiNode::set_automation_id(std::string_view value_arg) {
  automation_id_ = value_arg;
}


const std::string* UiNode::text() const {
  return text_ ? &(*text_) : nullptr;
}

void UiNode::set_text(const std::string_view* value_arg) {
  text_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UiNode::set_text(std::string_view value_arg) {
  text_ = value_arg;
}


const std::string* UiNode::label() const {
  return label_ ? &(*label_) : nullptr;
}

void UiNode::set_label(const std::string_view* value_arg) {
  label_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UiNode::set_label(std::string_view value_arg) {
  label_ = value_arg;
}


const std::string* UiNode::value() const {
  return value_ ? &(*value_) : nullptr;
}

void UiNode::set_value(const std::string_view* value_arg) {
  value_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UiNode::set_value(std::string_view value_arg) {
  value_ = value_arg;
}


const std::string& UiNode::role() const {
  return role_;
}

void UiNode::set_role(std::string_view value_arg) {
  role_ = value_arg;
}


const RectData& UiNode::bounds() const {
  return *bounds_;
}

void UiNode::set_bounds(const RectData& value_arg) {
  bounds_ = std::make_unique<RectData>(value_arg);
}


bool UiNode::enabled() const {
  return enabled_;
}

void UiNode::set_enabled(bool value_arg) {
  enabled_ = value_arg;
}


bool UiNode::clickable() const {
  return clickable_;
}

void UiNode::set_clickable(bool value_arg) {
  clickable_ = value_arg;
}


bool UiNode::editable() const {
  return editable_;
}

void UiNode::set_editable(bool value_arg) {
  editable_ = value_arg;
}


bool UiNode::focused() const {
  return focused_;
}

void UiNode::set_focused(bool value_arg) {
  focused_ = value_arg;
}


bool UiNode::selected() const {
  return selected_;
}

void UiNode::set_selected(bool value_arg) {
  selected_ = value_arg;
}


bool UiNode::checked() const {
  return checked_;
}

void UiNode::set_checked(bool value_arg) {
  checked_ = value_arg;
}


bool UiNode::scrollable() const {
  return scrollable_;
}

void UiNode::set_scrollable(bool value_arg) {
  scrollable_ = value_arg;
}


EncodableList UiNode::ToEncodableList() const {
  EncodableList list;
  list.reserve(16);
  list.push_back(EncodableValue(node_id_));
  list.push_back(parent_node_id_ ? EncodableValue(*parent_node_id_) : EncodableValue());
  list.push_back(EncodableValue(child_node_ids_));
  list.push_back(automation_id_ ? EncodableValue(*automation_id_) : EncodableValue());
  list.push_back(text_ ? EncodableValue(*text_) : EncodableValue());
  list.push_back(label_ ? EncodableValue(*label_) : EncodableValue());
  list.push_back(value_ ? EncodableValue(*value_) : EncodableValue());
  list.push_back(EncodableValue(role_));
  list.push_back(CustomEncodableValue(*bounds_));
  list.push_back(EncodableValue(enabled_));
  list.push_back(EncodableValue(clickable_));
  list.push_back(EncodableValue(editable_));
  list.push_back(EncodableValue(focused_));
  list.push_back(EncodableValue(selected_));
  list.push_back(EncodableValue(checked_));
  list.push_back(EncodableValue(scrollable_));
  return list;
}

UiNode UiNode::FromEncodableList(const EncodableList& list) {
  UiNode decoded(
    std::get<std::string>(list[0]),
    std::get<EncodableList>(list[2]),
    std::get<std::string>(list[7]),
    std::any_cast<const RectData&>(std::get<CustomEncodableValue>(list[8])),
    std::get<bool>(list[9]),
    std::get<bool>(list[10]),
    std::get<bool>(list[11]),
    std::get<bool>(list[12]),
    std::get<bool>(list[13]),
    std::get<bool>(list[14]),
    std::get<bool>(list[15]));
  auto& encodable_parent_node_id = list[1];
  if (!encodable_parent_node_id.IsNull()) {
    decoded.set_parent_node_id(std::get<std::string>(encodable_parent_node_id));
  }
  auto& encodable_automation_id = list[3];
  if (!encodable_automation_id.IsNull()) {
    decoded.set_automation_id(std::get<std::string>(encodable_automation_id));
  }
  auto& encodable_text = list[4];
  if (!encodable_text.IsNull()) {
    decoded.set_text(std::get<std::string>(encodable_text));
  }
  auto& encodable_label = list[5];
  if (!encodable_label.IsNull()) {
    decoded.set_label(std::get<std::string>(encodable_label));
  }
  auto& encodable_value = list[6];
  if (!encodable_value.IsNull()) {
    decoded.set_value(std::get<std::string>(encodable_value));
  }
  return decoded;
}

bool UiNode::operator==(const UiNode& other) const {
  return PigeonInternalDeepEquals(node_id_, other.node_id_) && PigeonInternalDeepEquals(parent_node_id_, other.parent_node_id_) && PigeonInternalDeepEquals(child_node_ids_, other.child_node_ids_) && PigeonInternalDeepEquals(automation_id_, other.automation_id_) && PigeonInternalDeepEquals(text_, other.text_) && PigeonInternalDeepEquals(label_, other.label_) && PigeonInternalDeepEquals(value_, other.value_) && PigeonInternalDeepEquals(role_, other.role_) && PigeonInternalDeepEquals(bounds_, other.bounds_) && PigeonInternalDeepEquals(enabled_, other.enabled_) && PigeonInternalDeepEquals(clickable_, other.clickable_) && PigeonInternalDeepEquals(editable_, other.editable_) && PigeonInternalDeepEquals(focused_, other.focused_) && PigeonInternalDeepEquals(selected_, other.selected_) && PigeonInternalDeepEquals(checked_, other.checked_) && PigeonInternalDeepEquals(scrollable_, other.scrollable_);
}

bool UiNode::operator!=(const UiNode& other) const {
  return !(*this == other);
}

size_t UiNode::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(node_id_);
  result = result * 31 + PigeonInternalDeepHash(parent_node_id_);
  result = result * 31 + PigeonInternalDeepHash(child_node_ids_);
  result = result * 31 + PigeonInternalDeepHash(automation_id_);
  result = result * 31 + PigeonInternalDeepHash(text_);
  result = result * 31 + PigeonInternalDeepHash(label_);
  result = result * 31 + PigeonInternalDeepHash(value_);
  result = result * 31 + PigeonInternalDeepHash(role_);
  result = result * 31 + PigeonInternalDeepHash(bounds_);
  result = result * 31 + PigeonInternalDeepHash(enabled_);
  result = result * 31 + PigeonInternalDeepHash(clickable_);
  result = result * 31 + PigeonInternalDeepHash(editable_);
  result = result * 31 + PigeonInternalDeepHash(focused_);
  result = result * 31 + PigeonInternalDeepHash(selected_);
  result = result * 31 + PigeonInternalDeepHash(checked_);
  result = result * 31 + PigeonInternalDeepHash(scrollable_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const UiNode& obj) {
  os << "UiNode(";
  os << "node_id: ";
  os << PigeonInternalToString(obj.node_id_);
  os << ", parent_node_id: ";
  if (obj.parent_node_id_) {
    os << PigeonInternalToString(*obj.parent_node_id_);
  }
  else {
    os << "null";
  }
  os << ", child_node_ids: ";
  os << PigeonInternalToString(obj.child_node_ids_);
  os << ", automation_id: ";
  if (obj.automation_id_) {
    os << PigeonInternalToString(*obj.automation_id_);
  }
  else {
    os << "null";
  }
  os << ", text: ";
  if (obj.text_) {
    os << PigeonInternalToString(*obj.text_);
  }
  else {
    os << "null";
  }
  os << ", label: ";
  if (obj.label_) {
    os << PigeonInternalToString(*obj.label_);
  }
  else {
    os << "null";
  }
  os << ", value: ";
  if (obj.value_) {
    os << PigeonInternalToString(*obj.value_);
  }
  else {
    os << "null";
  }
  os << ", role: ";
  os << PigeonInternalToString(obj.role_);
  os << ", bounds: ";
  os << obj.bounds_;
  os << ", enabled: ";
  os << PigeonInternalToString(obj.enabled_);
  os << ", clickable: ";
  os << PigeonInternalToString(obj.clickable_);
  os << ", editable: ";
  os << PigeonInternalToString(obj.editable_);
  os << ", focused: ";
  os << PigeonInternalToString(obj.focused_);
  os << ", selected: ";
  os << PigeonInternalToString(obj.selected_);
  os << ", checked: ";
  os << PigeonInternalToString(obj.checked_);
  os << ", scrollable: ";
  os << PigeonInternalToString(obj.scrollable_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const UiNode& v) {
  return v.Hash();
}

// UiSnapshot

UiSnapshot::UiSnapshot(
  int64_t generation,
  const EncodableList& nodes)
 : generation_(generation),
    nodes_(nodes) {}

int64_t UiSnapshot::generation() const {
  return generation_;
}

void UiSnapshot::set_generation(int64_t value_arg) {
  generation_ = value_arg;
}


const EncodableList& UiSnapshot::nodes() const {
  return nodes_;
}

void UiSnapshot::set_nodes(const EncodableList& value_arg) {
  nodes_ = value_arg;
}


EncodableList UiSnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(generation_));
  list.push_back(EncodableValue(nodes_));
  return list;
}

UiSnapshot UiSnapshot::FromEncodableList(const EncodableList& list) {
  UiSnapshot decoded(
    std::get<int64_t>(list[0]),
    std::get<EncodableList>(list[1]));
  return decoded;
}

bool UiSnapshot::operator==(const UiSnapshot& other) const {
  return PigeonInternalDeepEquals(generation_, other.generation_) && PigeonInternalDeepEquals(nodes_, other.nodes_);
}

bool UiSnapshot::operator!=(const UiSnapshot& other) const {
  return !(*this == other);
}

size_t UiSnapshot::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(generation_);
  result = result * 31 + PigeonInternalDeepHash(nodes_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const UiSnapshot& obj) {
  os << "UiSnapshot(";
  os << "generation: ";
  os << PigeonInternalToString(obj.generation_);
  os << ", nodes: ";
  os << PigeonInternalToString(obj.nodes_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const UiSnapshot& v) {
  return v.Hash();
}

// ActionResult

ActionResult::ActionResult(
  bool success,
  bool ui_changed)
 : success_(success),
    ui_changed_(ui_changed) {}

ActionResult::ActionResult(
  bool success,
  const std::string* message,
  bool ui_changed)
 : success_(success),
    message_(message ? std::optional<std::string>(*message) : std::nullopt),
    ui_changed_(ui_changed) {}

bool ActionResult::success() const {
  return success_;
}

void ActionResult::set_success(bool value_arg) {
  success_ = value_arg;
}


const std::string* ActionResult::message() const {
  return message_ ? &(*message_) : nullptr;
}

void ActionResult::set_message(const std::string_view* value_arg) {
  message_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ActionResult::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


bool ActionResult::ui_changed() const {
  return ui_changed_;
}

void ActionResult::set_ui_changed(bool value_arg) {
  ui_changed_ = value_arg;
}


EncodableList ActionResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(success_));
  list.push_back(message_ ? EncodableValue(*message_) : EncodableValue());
  list.push_back(EncodableValue(ui_changed_));
  return list;
}

ActionResult ActionResult::FromEncodableList(const EncodableList& list) {
  ActionResult decoded(
    std::get<bool>(list[0]),
    std::get<bool>(list[2]));
  auto& encodable_message = list[1];
  if (!encodable_message.IsNull()) {
    decoded.set_message(std::get<std::string>(encodable_message));
  }
  return decoded;
}

bool ActionResult::operator==(const ActionResult& other) const {
  return PigeonInternalDeepEquals(success_, other.success_) && PigeonInternalDeepEquals(message_, other.message_) && PigeonInternalDeepEquals(ui_changed_, other.ui_changed_);
}

bool ActionResult::operator!=(const ActionResult& other) const {
  return !(*this == other);
}

size_t ActionResult::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(success_);
  result = result * 31 + PigeonInternalDeepHash(message_);
  result = result * 31 + PigeonInternalDeepHash(ui_changed_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ActionResult& obj) {
  os << "ActionResult(";
  os << "success: ";
  os << PigeonInternalToString(obj.success_);
  os << ", message: ";
  if (obj.message_) {
    os << PigeonInternalToString(*obj.message_);
  }
  else {
    os << "null";
  }
  os << ", ui_changed: ";
  os << PigeonInternalToString(obj.ui_changed_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ActionResult& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<UiAction>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(DriverConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(DeviceInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(RectData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(UiNode::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(UiSnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(ActionResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(UiAction)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<UiAction>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DriverConfig)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<DriverConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DeviceInfo)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<DeviceInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RectData)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<RectData>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UiNode)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<UiNode>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UiSnapshot)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<UiSnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ActionResult)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<ActionResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by DeviceKitHostApi.
const ::flutter::StandardMessageCodec& DeviceKitHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `DeviceKitHostApi` to handle messages through the `binary_messenger`.
void DeviceKitHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  DeviceKitHostApi* api) {
  DeviceKitHostApi::SetUp(binary_messenger, api, "");
}

void DeviceKitHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  DeviceKitHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.initialize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_config_arg = args.at(0);
          if (encodable_config_arg.IsNull()) {
            reply(WrapError("config_arg unexpectedly null."));
            return;
          }
          const auto& config_arg = std::any_cast<const DriverConfig&>(std::get<CustomEncodableValue>(encodable_config_arg));
          std::optional<FlutterError> output = api->Initialize(config_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dispose" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Dispose();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getDeviceInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DeviceInfo> output = api->GetDeviceInfo();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.openAccessibilitySettings" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<ActionResult> output = api->OpenAccessibilitySettings();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.launchApp" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_package_name_arg = args.at(0);
          if (encodable_package_name_arg.IsNull()) {
            reply(WrapError("package_name_arg unexpectedly null."));
            return;
          }
          const auto& package_name_arg = std::get<std::string>(encodable_package_name_arg);
          ErrorOr<ActionResult> output = api->LaunchApp(package_name_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dumpUi" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<UiSnapshot> output = api->DumpUi();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.performElementAction" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_node_id_arg = args.at(0);
          if (encodable_node_id_arg.IsNull()) {
            reply(WrapError("node_id_arg unexpectedly null."));
            return;
          }
          const auto& node_id_arg = std::get<std::string>(encodable_node_id_arg);
          const auto& encodable_generation_arg = args.at(1);
          if (encodable_generation_arg.IsNull()) {
            reply(WrapError("generation_arg unexpectedly null."));
            return;
          }
          const int64_t generation_arg = encodable_generation_arg.LongValue();
          const auto& encodable_action_arg = args.at(2);
          if (encodable_action_arg.IsNull()) {
            reply(WrapError("action_arg unexpectedly null."));
            return;
          }
          const auto& action_arg = std::any_cast<const UiAction&>(std::get<CustomEncodableValue>(encodable_action_arg));
          const auto& encodable_value_arg = args.at(3);
          const auto* value_arg = std::get_if<std::string>(&encodable_value_arg);
          ErrorOr<ActionResult> output = api->PerformElementAction(node_id_arg, generation_arg, action_arg, value_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.tap" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_x_arg = args.at(0);
          if (encodable_x_arg.IsNull()) {
            reply(WrapError("x_arg unexpectedly null."));
            return;
          }
          const auto& x_arg = std::get<double>(encodable_x_arg);
          const auto& encodable_y_arg = args.at(1);
          if (encodable_y_arg.IsNull()) {
            reply(WrapError("y_arg unexpectedly null."));
            return;
          }
          const auto& y_arg = std::get<double>(encodable_y_arg);
          ErrorOr<ActionResult> output = api->Tap(x_arg, y_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.swipe" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_from_x_arg = args.at(0);
          if (encodable_from_x_arg.IsNull()) {
            reply(WrapError("from_x_arg unexpectedly null."));
            return;
          }
          const auto& from_x_arg = std::get<double>(encodable_from_x_arg);
          const auto& encodable_from_y_arg = args.at(1);
          if (encodable_from_y_arg.IsNull()) {
            reply(WrapError("from_y_arg unexpectedly null."));
            return;
          }
          const auto& from_y_arg = std::get<double>(encodable_from_y_arg);
          const auto& encodable_to_x_arg = args.at(2);
          if (encodable_to_x_arg.IsNull()) {
            reply(WrapError("to_x_arg unexpectedly null."));
            return;
          }
          const auto& to_x_arg = std::get<double>(encodable_to_x_arg);
          const auto& encodable_to_y_arg = args.at(3);
          if (encodable_to_y_arg.IsNull()) {
            reply(WrapError("to_y_arg unexpectedly null."));
            return;
          }
          const auto& to_y_arg = std::get<double>(encodable_to_y_arg);
          const auto& encodable_duration_ms_arg = args.at(4);
          if (encodable_duration_ms_arg.IsNull()) {
            reply(WrapError("duration_ms_arg unexpectedly null."));
            return;
          }
          const int64_t duration_ms_arg = encodable_duration_ms_arg.LongValue();
          ErrorOr<ActionResult> output = api->Swipe(from_x_arg, from_y_arg, to_x_arg, to_y_arg, duration_ms_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.typeText" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          ErrorOr<ActionResult> output = api->TypeText(text_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressBack" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<ActionResult> output = api->PressBack();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressHome" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<ActionResult> output = api->PressHome();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.screenshot" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::vector<uint8_t>> output = api->Screenshot();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.requestScreenCapture" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<ActionResult> output = api->RequestScreenCapture();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getClipboard" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<std::string>> output = api->GetClipboard();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.setClipboard" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          ErrorOr<ActionResult> output = api->SetClipboard(text_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue DeviceKitHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue DeviceKitHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace device_kit_lib
