// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hodoan.device_kit_lib

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class UiAction(val raw: Int) {
  PRESS(0),
  FOCUS(1),
  SET_VALUE(2),
  SCROLL_FORWARD(3),
  SCROLL_BACKWARD(4);

  companion object {
    fun ofRaw(raw: Int): UiAction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DriverConfig (
  val sessionId: String,
  val enableLogs: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DriverConfig {
      val sessionId = pigeonVar_list[0] as String
      val enableLogs = pigeonVar_list[1] as Boolean
      return DriverConfig(sessionId, enableLogs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      enableLogs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DriverConfig
    return MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.enableLogs, other.enableLogs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableLogs)
    return result
  }
  override fun toString(): String {
    return "DriverConfig(sessionId=$sessionId, enableLogs=$enableLogs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeviceInfo (
  val platform: String,
  val osVersion: String? = null,
  val model: String? = null,
  val deviceName: String? = null,
  val physicalDevice: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfo {
      val platform = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String?
      val model = pigeonVar_list[2] as String?
      val deviceName = pigeonVar_list[3] as String?
      val physicalDevice = pigeonVar_list[4] as Boolean
      return DeviceInfo(platform, osVersion, model, deviceName, physicalDevice)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      model,
      deviceName,
      physicalDevice,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceInfo
    return MessagesPigeonUtils.deepEquals(this.platform, other.platform) && MessagesPigeonUtils.deepEquals(this.osVersion, other.osVersion) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.deviceName, other.deviceName) && MessagesPigeonUtils.deepEquals(this.physicalDevice, other.physicalDevice)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platform)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.physicalDevice)
    return result
  }
  override fun toString(): String {
    return "DeviceInfo(platform=$platform, osVersion=$osVersion, model=$model, deviceName=$deviceName, physicalDevice=$physicalDevice)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RectData (
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RectData {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return RectData(x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RectData
    return MessagesPigeonUtils.deepEquals(this.x, other.x) && MessagesPigeonUtils.deepEquals(this.y, other.y) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.x)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.y)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "RectData(x=$x, y=$y, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UiNode (
  val nodeId: String,
  val parentNodeId: String? = null,
  val childNodeIds: List<String>,
  val automationId: String? = null,
  val text: String? = null,
  val label: String? = null,
  val value: String? = null,
  val role: String,
  val bounds: RectData,
  val enabled: Boolean,
  val clickable: Boolean,
  val editable: Boolean,
  val focused: Boolean,
  val selected: Boolean,
  val checked: Boolean,
  val scrollable: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UiNode {
      val nodeId = pigeonVar_list[0] as String
      val parentNodeId = pigeonVar_list[1] as String?
      val childNodeIds = pigeonVar_list[2] as List<String>
      val automationId = pigeonVar_list[3] as String?
      val text = pigeonVar_list[4] as String?
      val label = pigeonVar_list[5] as String?
      val value = pigeonVar_list[6] as String?
      val role = pigeonVar_list[7] as String
      val bounds = pigeonVar_list[8] as RectData
      val enabled = pigeonVar_list[9] as Boolean
      val clickable = pigeonVar_list[10] as Boolean
      val editable = pigeonVar_list[11] as Boolean
      val focused = pigeonVar_list[12] as Boolean
      val selected = pigeonVar_list[13] as Boolean
      val checked = pigeonVar_list[14] as Boolean
      val scrollable = pigeonVar_list[15] as Boolean
      return UiNode(nodeId, parentNodeId, childNodeIds, automationId, text, label, value, role, bounds, enabled, clickable, editable, focused, selected, checked, scrollable)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nodeId,
      parentNodeId,
      childNodeIds,
      automationId,
      text,
      label,
      value,
      role,
      bounds,
      enabled,
      clickable,
      editable,
      focused,
      selected,
      checked,
      scrollable,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UiNode
    return MessagesPigeonUtils.deepEquals(this.nodeId, other.nodeId) && MessagesPigeonUtils.deepEquals(this.parentNodeId, other.parentNodeId) && MessagesPigeonUtils.deepEquals(this.childNodeIds, other.childNodeIds) && MessagesPigeonUtils.deepEquals(this.automationId, other.automationId) && MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.label, other.label) && MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.role, other.role) && MessagesPigeonUtils.deepEquals(this.bounds, other.bounds) && MessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && MessagesPigeonUtils.deepEquals(this.clickable, other.clickable) && MessagesPigeonUtils.deepEquals(this.editable, other.editable) && MessagesPigeonUtils.deepEquals(this.focused, other.focused) && MessagesPigeonUtils.deepEquals(this.selected, other.selected) && MessagesPigeonUtils.deepEquals(this.checked, other.checked) && MessagesPigeonUtils.deepEquals(this.scrollable, other.scrollable)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nodeId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.parentNodeId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.childNodeIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.automationId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.label)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.role)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bounds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clickable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.editable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.focused)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selected)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.checked)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scrollable)
    return result
  }
  override fun toString(): String {
    return "UiNode(nodeId=$nodeId, parentNodeId=$parentNodeId, childNodeIds=$childNodeIds, automationId=$automationId, text=$text, label=$label, value=$value, role=$role, bounds=$bounds, enabled=$enabled, clickable=$clickable, editable=$editable, focused=$focused, selected=$selected, checked=$checked, scrollable=$scrollable)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UiSnapshot (
  val generation: Long,
  val nodes: List<UiNode>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UiSnapshot {
      val generation = pigeonVar_list[0] as Long
      val nodes = pigeonVar_list[1] as List<UiNode>
      return UiSnapshot(generation, nodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      generation,
      nodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UiSnapshot
    return MessagesPigeonUtils.deepEquals(this.generation, other.generation) && MessagesPigeonUtils.deepEquals(this.nodes, other.nodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.generation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nodes)
    return result
  }
  override fun toString(): String {
    return "UiSnapshot(generation=$generation, nodes=$nodes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ActionResult (
  val success: Boolean,
  val message: String? = null,
  val uiChanged: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ActionResult {
      val success = pigeonVar_list[0] as Boolean
      val message = pigeonVar_list[1] as String?
      val uiChanged = pigeonVar_list[2] as Boolean
      return ActionResult(success, message, uiChanged)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      message,
      uiChanged,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ActionResult
    return MessagesPigeonUtils.deepEquals(this.success, other.success) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.uiChanged, other.uiChanged)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.success)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uiChanged)
    return result
  }
  override fun toString(): String {
    return "ActionResult(success=$success, message=$message, uiChanged=$uiChanged)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          UiAction.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DriverConfig.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RectData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UiNode.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UiSnapshot.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ActionResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is UiAction -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is DriverConfig -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DeviceInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RectData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is UiNode -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is UiSnapshot -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ActionResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DeviceKitHostApi {
  fun initialize(config: DriverConfig)
  fun dispose()
  fun getDeviceInfo(): DeviceInfo
  fun openAccessibilitySettings(): ActionResult
  fun launchApp(packageName: String): ActionResult
  fun dumpUi(): UiSnapshot
  fun performElementAction(nodeId: String, generation: Long, action: UiAction, value: String?): ActionResult
  fun tap(x: Double, y: Double): ActionResult
  fun swipe(fromX: Double, fromY: Double, toX: Double, toY: Double, durationMs: Long): ActionResult
  fun typeText(text: String): ActionResult
  fun pressBack(): ActionResult
  fun pressHome(): ActionResult
  fun screenshot(): ByteArray
  fun requestScreenCapture(): ActionResult
  fun getClipboard(): String?
  fun setClipboard(text: String): ActionResult

  companion object {
    /** The codec used by DeviceKitHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `DeviceKitHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceKitHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as DriverConfig
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceInfo())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openAccessibilitySettings())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.launchApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.launchApp(packageNameArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dumpUi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.dumpUi())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.performElementAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as String
            val generationArg = args[1] as Long
            val actionArg = args[2] as UiAction
            val valueArg = args[3] as String?
            val wrapped: List<Any?> = try {
              listOf(api.performElementAction(nodeIdArg, generationArg, actionArg, valueArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.tap$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            val wrapped: List<Any?> = try {
              listOf(api.tap(xArg, yArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.swipe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromXArg = args[0] as Double
            val fromYArg = args[1] as Double
            val toXArg = args[2] as Double
            val toYArg = args[3] as Double
            val durationMsArg = args[4] as Long
            val wrapped: List<Any?> = try {
              listOf(api.swipe(fromXArg, fromYArg, toXArg, toYArg, durationMsArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.typeText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.typeText(textArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressBack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.pressBack())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressHome$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.pressHome())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.screenshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.screenshot())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.requestScreenCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestScreenCapture())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getClipboard())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.setClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.setClipboard(textArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
