// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum UiAction: Int, CaseIterable {
  case press = 0
  case focus = 1
  case setValue = 2
  case scrollForward = 3
  case scrollBackward = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct DriverConfig: Hashable, CustomStringConvertible {
  var sessionId: String
  var enableLogs: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DriverConfig? {
    let sessionId = pigeonVar_list[0] as! String
    let enableLogs = pigeonVar_list[1] as! Bool

    return DriverConfig(
      sessionId: sessionId,
      enableLogs: enableLogs
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      enableLogs,
    ]
  }
  static func == (lhs: DriverConfig, rhs: DriverConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.enableLogs, rhs.enableLogs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DriverConfig")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableLogs, hasher: &hasher)
  }

  public var description: String {
    return "DriverConfig(sessionId: \(String(describing: sessionId)), enableLogs: \(String(describing: enableLogs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfo: Hashable, CustomStringConvertible {
  var platform: String
  var osVersion: String? = nil
  var model: String? = nil
  var deviceName: String? = nil
  var physicalDevice: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfo? {
    let platform = pigeonVar_list[0] as! String
    let osVersion: String? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])
    let deviceName: String? = nilOrValue(pigeonVar_list[3])
    let physicalDevice = pigeonVar_list[4] as! Bool

    return DeviceInfo(
      platform: platform,
      osVersion: osVersion,
      model: model,
      deviceName: deviceName,
      physicalDevice: physicalDevice
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      osVersion,
      model,
      deviceName,
      physicalDevice,
    ]
  }
  static func == (lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && MessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.deviceName, rhs.deviceName) && MessagesPigeonInternal.deepEquals(lhs.physicalDevice, rhs.physicalDevice)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceInfo")
    MessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: physicalDevice, hasher: &hasher)
  }

  public var description: String {
    return "DeviceInfo(platform: \(String(describing: platform)), osVersion: \(String(describing: osVersion)), model: \(String(describing: model)), deviceName: \(String(describing: deviceName)), physicalDevice: \(String(describing: physicalDevice)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RectData: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RectData? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return RectData(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: RectData, rhs: RectData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RectData")
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "RectData(x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UiNode: Hashable, CustomStringConvertible {
  var nodeId: String
  var parentNodeId: String? = nil
  var childNodeIds: [String]
  var automationId: String? = nil
  var text: String? = nil
  var label: String? = nil
  var value: String? = nil
  var role: String
  var bounds: RectData
  var enabled: Bool
  var clickable: Bool
  var editable: Bool
  var focused: Bool
  var selected: Bool
  var checked: Bool
  var scrollable: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UiNode? {
    let nodeId = pigeonVar_list[0] as! String
    let parentNodeId: String? = nilOrValue(pigeonVar_list[1])
    let childNodeIds = pigeonVar_list[2] as! [String]
    let automationId: String? = nilOrValue(pigeonVar_list[3])
    let text: String? = nilOrValue(pigeonVar_list[4])
    let label: String? = nilOrValue(pigeonVar_list[5])
    let value: String? = nilOrValue(pigeonVar_list[6])
    let role = pigeonVar_list[7] as! String
    let bounds = pigeonVar_list[8] as! RectData
    let enabled = pigeonVar_list[9] as! Bool
    let clickable = pigeonVar_list[10] as! Bool
    let editable = pigeonVar_list[11] as! Bool
    let focused = pigeonVar_list[12] as! Bool
    let selected = pigeonVar_list[13] as! Bool
    let checked = pigeonVar_list[14] as! Bool
    let scrollable = pigeonVar_list[15] as! Bool

    return UiNode(
      nodeId: nodeId,
      parentNodeId: parentNodeId,
      childNodeIds: childNodeIds,
      automationId: automationId,
      text: text,
      label: label,
      value: value,
      role: role,
      bounds: bounds,
      enabled: enabled,
      clickable: clickable,
      editable: editable,
      focused: focused,
      selected: selected,
      checked: checked,
      scrollable: scrollable
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      parentNodeId,
      childNodeIds,
      automationId,
      text,
      label,
      value,
      role,
      bounds,
      enabled,
      clickable,
      editable,
      focused,
      selected,
      checked,
      scrollable,
    ]
  }
  static func == (lhs: UiNode, rhs: UiNode) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.nodeId, rhs.nodeId) && MessagesPigeonInternal.deepEquals(lhs.parentNodeId, rhs.parentNodeId) && MessagesPigeonInternal.deepEquals(lhs.childNodeIds, rhs.childNodeIds) && MessagesPigeonInternal.deepEquals(lhs.automationId, rhs.automationId) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.role, rhs.role) && MessagesPigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && MessagesPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MessagesPigeonInternal.deepEquals(lhs.clickable, rhs.clickable) && MessagesPigeonInternal.deepEquals(lhs.editable, rhs.editable) && MessagesPigeonInternal.deepEquals(lhs.focused, rhs.focused) && MessagesPigeonInternal.deepEquals(lhs.selected, rhs.selected) && MessagesPigeonInternal.deepEquals(lhs.checked, rhs.checked) && MessagesPigeonInternal.deepEquals(lhs.scrollable, rhs.scrollable)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UiNode")
    MessagesPigeonInternal.deepHash(value: nodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parentNodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: childNodeIds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: automationId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: role, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bounds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clickable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: editable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: focused, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selected, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: checked, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scrollable, hasher: &hasher)
  }

  public var description: String {
    return "UiNode(nodeId: \(String(describing: nodeId)), parentNodeId: \(String(describing: parentNodeId)), childNodeIds: \(String(describing: childNodeIds)), automationId: \(String(describing: automationId)), text: \(String(describing: text)), label: \(String(describing: label)), value: \(String(describing: value)), role: \(String(describing: role)), bounds: \(String(describing: bounds)), enabled: \(String(describing: enabled)), clickable: \(String(describing: clickable)), editable: \(String(describing: editable)), focused: \(String(describing: focused)), selected: \(String(describing: selected)), checked: \(String(describing: checked)), scrollable: \(String(describing: scrollable)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UiSnapshot: Hashable, CustomStringConvertible {
  var generation: Int64
  var nodes: [UiNode]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UiSnapshot? {
    let generation = pigeonVar_list[0] as! Int64
    let nodes = pigeonVar_list[1] as! [UiNode]

    return UiSnapshot(
      generation: generation,
      nodes: nodes
    )
  }
  func toList() -> [Any?] {
    return [
      generation,
      nodes,
    ]
  }
  static func == (lhs: UiSnapshot, rhs: UiSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation) && MessagesPigeonInternal.deepEquals(lhs.nodes, rhs.nodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UiSnapshot")
    MessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nodes, hasher: &hasher)
  }

  public var description: String {
    return "UiSnapshot(generation: \(String(describing: generation)), nodes: \(String(describing: nodes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ActionResult: Hashable, CustomStringConvertible {
  var success: Bool
  var message: String? = nil
  var uiChanged: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActionResult? {
    let success = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])
    let uiChanged = pigeonVar_list[2] as! Bool

    return ActionResult(
      success: success,
      message: message,
      uiChanged: uiChanged
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      message,
      uiChanged,
    ]
  }
  static func == (lhs: ActionResult, rhs: ActionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.success, rhs.success) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.uiChanged, rhs.uiChanged)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ActionResult")
    MessagesPigeonInternal.deepHash(value: success, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uiChanged, hasher: &hasher)
  }

  public var description: String {
    return "ActionResult(success: \(String(describing: success)), message: \(String(describing: message)), uiChanged: \(String(describing: uiChanged)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UiAction(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DriverConfig.fromList(self.readValue() as! [Any?])
    case 131:
      return DeviceInfo.fromList(self.readValue() as! [Any?])
    case 132:
      return RectData.fromList(self.readValue() as! [Any?])
    case 133:
      return UiNode.fromList(self.readValue() as! [Any?])
    case 134:
      return UiSnapshot.fromList(self.readValue() as! [Any?])
    case 135:
      return ActionResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? UiAction {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DriverConfig {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceInfo {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RectData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? UiNode {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? UiSnapshot {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ActionResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceKitHostApi {
  func initialize(config: DriverConfig) throws
  func dispose() throws
  func getDeviceInfo() throws -> DeviceInfo
  func openAccessibilitySettings() throws -> ActionResult
  func launchApp(packageName: String) throws -> ActionResult
  func dumpUi() throws -> UiSnapshot
  func performElementAction(nodeId: String, generation: Int64, action: UiAction, value: String?) throws -> ActionResult
  func tap(x: Double, y: Double) throws -> ActionResult
  func swipe(fromX: Double, fromY: Double, toX: Double, toY: Double, durationMs: Int64) throws -> ActionResult
  func typeText(text: String) throws -> ActionResult
  func pressBack() throws -> ActionResult
  func pressHome() throws -> ActionResult
  func screenshot() throws -> FlutterStandardTypedData
  func requestScreenCapture() throws -> ActionResult
  func getClipboard() throws -> String?
  func setClipboard(text: String) throws -> ActionResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DeviceKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! DriverConfig
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
    let openAccessibilitySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.openAccessibilitySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAccessibilitySettingsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.openAccessibilitySettings()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openAccessibilitySettingsChannel.setMessageHandler(nil)
    }
    let launchAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.launchApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchAppChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let packageNameArg = args[0] as! String
        do {
          let result = try api.launchApp(packageName: packageNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      launchAppChannel.setMessageHandler(nil)
    }
    let dumpUiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dumpUi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dumpUiChannel.setMessageHandler { _, reply in
        do {
          let result = try api.dumpUi()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      dumpUiChannel.setMessageHandler(nil)
    }
    let performElementActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.performElementAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      performElementActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! String
        let generationArg = args[1] as! Int64
        let actionArg = args[2] as! UiAction
        let valueArg: String? = nilOrValue(args[3])
        do {
          let result = try api.performElementAction(nodeId: nodeIdArg, generation: generationArg, action: actionArg, value: valueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      performElementActionChannel.setMessageHandler(nil)
    }
    let tapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.tap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      tapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] as! Double
        let yArg = args[1] as! Double
        do {
          let result = try api.tap(x: xArg, y: yArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      tapChannel.setMessageHandler(nil)
    }
    let swipeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.swipe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      swipeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromXArg = args[0] as! Double
        let fromYArg = args[1] as! Double
        let toXArg = args[2] as! Double
        let toYArg = args[3] as! Double
        let durationMsArg = args[4] as! Int64
        do {
          let result = try api.swipe(fromX: fromXArg, fromY: fromYArg, toX: toXArg, toY: toYArg, durationMs: durationMsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      swipeChannel.setMessageHandler(nil)
    }
    let typeTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.typeText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      typeTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          let result = try api.typeText(text: textArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      typeTextChannel.setMessageHandler(nil)
    }
    let pressBackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressBack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pressBackChannel.setMessageHandler { _, reply in
        do {
          let result = try api.pressBack()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pressBackChannel.setMessageHandler(nil)
    }
    let pressHomeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressHome\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pressHomeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.pressHome()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pressHomeChannel.setMessageHandler(nil)
    }
    let screenshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.screenshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      screenshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.screenshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      screenshotChannel.setMessageHandler(nil)
    }
    let requestScreenCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.requestScreenCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestScreenCaptureChannel.setMessageHandler { _, reply in
        do {
          let result = try api.requestScreenCapture()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestScreenCaptureChannel.setMessageHandler(nil)
    }
    let getClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getClipboardChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getClipboard()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getClipboardChannel.setMessageHandler(nil)
    }
    let setClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.setClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setClipboardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          let result = try api.setClipboard(text: textArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setClipboardChannel.setMessageHandler(nil)
    }
  }
}
