// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum AutomationCapability: Int, CaseIterable {
  case uiDump = 0
  case semanticAction = 1
  case pointerInput = 2
  case keyboardInput = 3
  case screenshot = 4
  case clipboard = 5
  case appLifecycle = 6
  case windowManagement = 7
  case systemAction = 8
}

enum AutomationPermission: Int, CaseIterable {
  case accessibility = 0
  case screenRecording = 1
  case inputMonitoring = 2
}

enum PermissionState: Int, CaseIterable {
  case unknown = 0
  case denied = 1
  case granted = 2
  case restricted = 3
}

enum TargetType: Int, CaseIterable {
  case application = 0
  case window = 1
  case systemUi = 2
}

enum UiRole: Int, CaseIterable {
  case unknown = 0
  case application = 1
  case window = 2
  case dialog = 3
  case button = 4
  case text = 5
  case textField = 6
  case image = 7
  case checkbox = 8
  case radio = 9
  case switchControl = 10
  case slider = 11
  case list = 12
  case listItem = 13
  case menu = 14
  case menuItem = 15
  case tab = 16
  case link = 17
  case scrollView = 18
}

enum UiAction: Int, CaseIterable {
  case press = 0
  case focus = 1
  case setValue = 2
  case increment = 3
  case decrement = 4
  case toggle = 5
  case select = 6
  case expand = 7
  case collapse = 8
  case dismiss = 9
  case scrollForward = 10
  case scrollBackward = 11
}

enum SystemAction: Int, CaseIterable {
  case back = 0
  case home = 1
  case escape = 2
  case appSwitcher = 3
  case notificationCenter = 4
  case quickSettings = 5
}

enum KeyAction: Int, CaseIterable {
  case press = 0
  case down = 1
  case up = 2
}

enum ScreenshotFormat: Int, CaseIterable {
  case png = 0
  case jpeg = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PointData: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PointData? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return PointData(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PointData, rhs: PointData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PointData")
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
  }

  public var description: String {
    return "PointData(x: \(String(describing: x)), y: \(String(describing: y)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RectData: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RectData? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return RectData(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: RectData, rhs: RectData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RectData")
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "RectData(x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SizeData: Hashable, CustomStringConvertible {
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SizeData? {
    let width = pigeonVar_list[0] as! Double
    let height = pigeonVar_list[1] as! Double

    return SizeData(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: SizeData, rhs: SizeData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SizeData")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "SizeData(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DriverConfig: Hashable, CustomStringConvertible {
  var sessionId: String
  var enableLogs: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DriverConfig? {
    let sessionId = pigeonVar_list[0] as! String
    let enableLogs = pigeonVar_list[1] as! Bool

    return DriverConfig(
      sessionId: sessionId,
      enableLogs: enableLogs
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      enableLogs,
    ]
  }
  static func == (lhs: DriverConfig, rhs: DriverConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.enableLogs, rhs.enableLogs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DriverConfig")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableLogs, hasher: &hasher)
  }

  public var description: String {
    return "DriverConfig(sessionId: \(String(describing: sessionId)), enableLogs: \(String(describing: enableLogs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfo: Hashable, CustomStringConvertible {
  var platform: String
  var osVersion: String? = nil
  var model: String? = nil
  var deviceName: String? = nil
  var physicalDevice: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfo? {
    let platform = pigeonVar_list[0] as! String
    let osVersion: String? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])
    let deviceName: String? = nilOrValue(pigeonVar_list[3])
    let physicalDevice = pigeonVar_list[4] as! Bool

    return DeviceInfo(
      platform: platform,
      osVersion: osVersion,
      model: model,
      deviceName: deviceName,
      physicalDevice: physicalDevice
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      osVersion,
      model,
      deviceName,
      physicalDevice,
    ]
  }
  static func == (lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && MessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.deviceName, rhs.deviceName) && MessagesPigeonInternal.deepEquals(lhs.physicalDevice, rhs.physicalDevice)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceInfo")
    MessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: physicalDevice, hasher: &hasher)
  }

  public var description: String {
    return "DeviceInfo(platform: \(String(describing: platform)), osVersion: \(String(describing: osVersion)), model: \(String(describing: model)), deviceName: \(String(describing: deviceName)), physicalDevice: \(String(describing: physicalDevice)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScreenInfo: Hashable, CustomStringConvertible {
  var size: SizeData
  var scale: Double
  var orientation: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScreenInfo? {
    let size = pigeonVar_list[0] as! SizeData
    let scale = pigeonVar_list[1] as! Double
    let orientation = pigeonVar_list[2] as! String

    return ScreenInfo(
      size: size,
      scale: scale,
      orientation: orientation
    )
  }
  func toList() -> [Any?] {
    return [
      size,
      scale,
      orientation,
    ]
  }
  static func == (lhs: ScreenInfo, rhs: ScreenInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.size, rhs.size) && MessagesPigeonInternal.deepEquals(lhs.scale, rhs.scale) && MessagesPigeonInternal.deepEquals(lhs.orientation, rhs.orientation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScreenInfo")
    MessagesPigeonInternal.deepHash(value: size, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: orientation, hasher: &hasher)
  }

  public var description: String {
    return "ScreenInfo(size: \(String(describing: size)), scale: \(String(describing: scale)), orientation: \(String(describing: orientation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CapabilityInfo: Hashable, CustomStringConvertible {
  var capabilities: [AutomationCapability?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CapabilityInfo? {
    let capabilities = pigeonVar_list[0] as! [AutomationCapability?]

    return CapabilityInfo(
      capabilities: capabilities
    )
  }
  func toList() -> [Any?] {
    return [
      capabilities
    ]
  }
  static func == (lhs: CapabilityInfo, rhs: CapabilityInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CapabilityInfo")
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
  }

  public var description: String {
    return "CapabilityInfo(capabilities: \(String(describing: capabilities)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PermissionInfo: Hashable, CustomStringConvertible {
  var permission: AutomationPermission
  var state: PermissionState
  var canRequest: Bool
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionInfo? {
    let permission = pigeonVar_list[0] as! AutomationPermission
    let state = pigeonVar_list[1] as! PermissionState
    let canRequest = pigeonVar_list[2] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[3])

    return PermissionInfo(
      permission: permission,
      state: state,
      canRequest: canRequest,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      permission,
      state,
      canRequest,
      message,
    ]
  }
  static func == (lhs: PermissionInfo, rhs: PermissionInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.permission, rhs.permission) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.canRequest, rhs.canRequest) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PermissionInfo")
    MessagesPigeonInternal.deepHash(value: permission, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canRequest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "PermissionInfo(permission: \(String(describing: permission)), state: \(String(describing: state)), canRequest: \(String(describing: canRequest)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TargetInfo: Hashable, CustomStringConvertible {
  var targetId: String
  var type: TargetType
  var appId: String? = nil
  var name: String? = nil
  var title: String? = nil
  var processId: Int64? = nil
  var bounds: RectData? = nil
  var foreground: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TargetInfo? {
    let targetId = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! TargetType
    let appId: String? = nilOrValue(pigeonVar_list[2])
    let name: String? = nilOrValue(pigeonVar_list[3])
    let title: String? = nilOrValue(pigeonVar_list[4])
    let processId: Int64? = nilOrValue(pigeonVar_list[5])
    let bounds: RectData? = nilOrValue(pigeonVar_list[6])
    let foreground = pigeonVar_list[7] as! Bool

    return TargetInfo(
      targetId: targetId,
      type: type,
      appId: appId,
      name: name,
      title: title,
      processId: processId,
      bounds: bounds,
      foreground: foreground
    )
  }
  func toList() -> [Any?] {
    return [
      targetId,
      type,
      appId,
      name,
      title,
      processId,
      bounds,
      foreground,
    ]
  }
  static func == (lhs: TargetInfo, rhs: TargetInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.appId, rhs.appId) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.processId, rhs.processId) && MessagesPigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && MessagesPigeonInternal.deepEquals(lhs.foreground, rhs.foreground)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TargetInfo")
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: processId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bounds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: foreground, hasher: &hasher)
  }

  public var description: String {
    return "TargetInfo(targetId: \(String(describing: targetId)), type: \(String(describing: type)), appId: \(String(describing: appId)), name: \(String(describing: name)), title: \(String(describing: title)), processId: \(String(describing: processId)), bounds: \(String(describing: bounds)), foreground: \(String(describing: foreground)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UiNode: Hashable, CustomStringConvertible {
  var nodeId: String
  var parentNodeId: String? = nil
  var childNodeIds: [String?]? = nil
  var automationId: String? = nil
  var text: String? = nil
  var label: String? = nil
  var value: String? = nil
  var role: UiRole
  var bounds: RectData
  var visible: Bool
  var enabled: Bool
  var clickable: Bool
  var editable: Bool
  var focused: Bool
  var selected: Bool
  var checked: Bool
  var scrollable: Bool
  var actions: [UiAction?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UiNode? {
    let nodeId = pigeonVar_list[0] as! String
    let parentNodeId: String? = nilOrValue(pigeonVar_list[1])
    let childNodeIds: [String?]? = nilOrValue(pigeonVar_list[2])
    let automationId: String? = nilOrValue(pigeonVar_list[3])
    let text: String? = nilOrValue(pigeonVar_list[4])
    let label: String? = nilOrValue(pigeonVar_list[5])
    let value: String? = nilOrValue(pigeonVar_list[6])
    let role = pigeonVar_list[7] as! UiRole
    let bounds = pigeonVar_list[8] as! RectData
    let visible = pigeonVar_list[9] as! Bool
    let enabled = pigeonVar_list[10] as! Bool
    let clickable = pigeonVar_list[11] as! Bool
    let editable = pigeonVar_list[12] as! Bool
    let focused = pigeonVar_list[13] as! Bool
    let selected = pigeonVar_list[14] as! Bool
    let checked = pigeonVar_list[15] as! Bool
    let scrollable = pigeonVar_list[16] as! Bool
    let actions: [UiAction?]? = nilOrValue(pigeonVar_list[17])

    return UiNode(
      nodeId: nodeId,
      parentNodeId: parentNodeId,
      childNodeIds: childNodeIds,
      automationId: automationId,
      text: text,
      label: label,
      value: value,
      role: role,
      bounds: bounds,
      visible: visible,
      enabled: enabled,
      clickable: clickable,
      editable: editable,
      focused: focused,
      selected: selected,
      checked: checked,
      scrollable: scrollable,
      actions: actions
    )
  }
  func toList() -> [Any?] {
    return [
      nodeId,
      parentNodeId,
      childNodeIds,
      automationId,
      text,
      label,
      value,
      role,
      bounds,
      visible,
      enabled,
      clickable,
      editable,
      focused,
      selected,
      checked,
      scrollable,
      actions,
    ]
  }
  static func == (lhs: UiNode, rhs: UiNode) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.nodeId, rhs.nodeId) && MessagesPigeonInternal.deepEquals(lhs.parentNodeId, rhs.parentNodeId) && MessagesPigeonInternal.deepEquals(lhs.childNodeIds, rhs.childNodeIds) && MessagesPigeonInternal.deepEquals(lhs.automationId, rhs.automationId) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.role, rhs.role) && MessagesPigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && MessagesPigeonInternal.deepEquals(lhs.visible, rhs.visible) && MessagesPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MessagesPigeonInternal.deepEquals(lhs.clickable, rhs.clickable) && MessagesPigeonInternal.deepEquals(lhs.editable, rhs.editable) && MessagesPigeonInternal.deepEquals(lhs.focused, rhs.focused) && MessagesPigeonInternal.deepEquals(lhs.selected, rhs.selected) && MessagesPigeonInternal.deepEquals(lhs.checked, rhs.checked) && MessagesPigeonInternal.deepEquals(lhs.scrollable, rhs.scrollable) && MessagesPigeonInternal.deepEquals(lhs.actions, rhs.actions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UiNode")
    MessagesPigeonInternal.deepHash(value: nodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parentNodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: childNodeIds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: automationId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: role, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bounds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: visible, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clickable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: editable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: focused, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selected, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: checked, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scrollable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: actions, hasher: &hasher)
  }

  public var description: String {
    return "UiNode(nodeId: \(String(describing: nodeId)), parentNodeId: \(String(describing: parentNodeId)), childNodeIds: \(String(describing: childNodeIds)), automationId: \(String(describing: automationId)), text: \(String(describing: text)), label: \(String(describing: label)), value: \(String(describing: value)), role: \(String(describing: role)), bounds: \(String(describing: bounds)), visible: \(String(describing: visible)), enabled: \(String(describing: enabled)), clickable: \(String(describing: clickable)), editable: \(String(describing: editable)), focused: \(String(describing: focused)), selected: \(String(describing: selected)), checked: \(String(describing: checked)), scrollable: \(String(describing: scrollable)), actions: \(String(describing: actions)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UiSnapshot: Hashable, CustomStringConvertible {
  var generation: Int64
  var targetId: String? = nil
  var rootNodeId: String? = nil
  var screen: ScreenInfo
  var nodes: [UiNode?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UiSnapshot? {
    let generation = pigeonVar_list[0] as! Int64
    let targetId: String? = nilOrValue(pigeonVar_list[1])
    let rootNodeId: String? = nilOrValue(pigeonVar_list[2])
    let screen = pigeonVar_list[3] as! ScreenInfo
    let nodes = pigeonVar_list[4] as! [UiNode?]

    return UiSnapshot(
      generation: generation,
      targetId: targetId,
      rootNodeId: rootNodeId,
      screen: screen,
      nodes: nodes
    )
  }
  func toList() -> [Any?] {
    return [
      generation,
      targetId,
      rootNodeId,
      screen,
      nodes,
    ]
  }
  static func == (lhs: UiSnapshot, rhs: UiSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation) && MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.rootNodeId, rhs.rootNodeId) && MessagesPigeonInternal.deepEquals(lhs.screen, rhs.screen) && MessagesPigeonInternal.deepEquals(lhs.nodes, rhs.nodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UiSnapshot")
    MessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rootNodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screen, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nodes, hasher: &hasher)
  }

  public var description: String {
    return "UiSnapshot(generation: \(String(describing: generation)), targetId: \(String(describing: targetId)), rootNodeId: \(String(describing: rootNodeId)), screen: \(String(describing: screen)), nodes: \(String(describing: nodes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DumpUiRequest: Hashable, CustomStringConvertible {
  var targetId: String? = nil
  var includeInvisible: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DumpUiRequest? {
    let targetId: String? = nilOrValue(pigeonVar_list[0])
    let includeInvisible = pigeonVar_list[1] as! Bool

    return DumpUiRequest(
      targetId: targetId,
      includeInvisible: includeInvisible
    )
  }
  func toList() -> [Any?] {
    return [
      targetId,
      includeInvisible,
    ]
  }
  static func == (lhs: DumpUiRequest, rhs: DumpUiRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.includeInvisible, rhs.includeInvisible)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DumpUiRequest")
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includeInvisible, hasher: &hasher)
  }

  public var description: String {
    return "DumpUiRequest(targetId: \(String(describing: targetId)), includeInvisible: \(String(describing: includeInvisible)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HitTestRequest: Hashable, CustomStringConvertible {
  var targetId: String? = nil
  var point: PointData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HitTestRequest? {
    let targetId: String? = nilOrValue(pigeonVar_list[0])
    let point = pigeonVar_list[1] as! PointData

    return HitTestRequest(
      targetId: targetId,
      point: point
    )
  }
  func toList() -> [Any?] {
    return [
      targetId,
      point,
    ]
  }
  static func == (lhs: HitTestRequest, rhs: HitTestRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.point, rhs.point)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HitTestRequest")
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: point, hasher: &hasher)
  }

  public var description: String {
    return "HitTestRequest(targetId: \(String(describing: targetId)), point: \(String(describing: point)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ElementActionRequest: Hashable, CustomStringConvertible {
  var targetId: String? = nil
  var generation: Int64
  var nodeId: String
  var action: UiAction
  var value: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ElementActionRequest? {
    let targetId: String? = nilOrValue(pigeonVar_list[0])
    let generation = pigeonVar_list[1] as! Int64
    let nodeId = pigeonVar_list[2] as! String
    let action = pigeonVar_list[3] as! UiAction
    let value: String? = nilOrValue(pigeonVar_list[4])

    return ElementActionRequest(
      targetId: targetId,
      generation: generation,
      nodeId: nodeId,
      action: action,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      targetId,
      generation,
      nodeId,
      action,
      value,
    ]
  }
  static func == (lhs: ElementActionRequest, rhs: ElementActionRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.generation, rhs.generation) && MessagesPigeonInternal.deepEquals(lhs.nodeId, rhs.nodeId) && MessagesPigeonInternal.deepEquals(lhs.action, rhs.action) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ElementActionRequest")
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: generation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nodeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: action, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "ElementActionRequest(targetId: \(String(describing: targetId)), generation: \(String(describing: generation)), nodeId: \(String(describing: nodeId)), action: \(String(describing: action)), value: \(String(describing: value)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ActionResult: Hashable, CustomStringConvertible {
  var success: Bool
  var message: String? = nil
  var uiChanged: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActionResult? {
    let success = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])
    let uiChanged = pigeonVar_list[2] as! Bool

    return ActionResult(
      success: success,
      message: message,
      uiChanged: uiChanged
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      message,
      uiChanged,
    ]
  }
  static func == (lhs: ActionResult, rhs: ActionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.success, rhs.success) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.uiChanged, rhs.uiChanged)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ActionResult")
    MessagesPigeonInternal.deepHash(value: success, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uiChanged, hasher: &hasher)
  }

  public var description: String {
    return "ActionResult(success: \(String(describing: success)), message: \(String(describing: message)), uiChanged: \(String(describing: uiChanged)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LaunchAppRequest: Hashable, CustomStringConvertible {
  var appId: String
  var arguments: [String?]? = nil
  var environment: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LaunchAppRequest? {
    let appId = pigeonVar_list[0] as! String
    let arguments: [String?]? = nilOrValue(pigeonVar_list[1])
    let environment: [String?: String?]? = nilOrValue(pigeonVar_list[2])

    return LaunchAppRequest(
      appId: appId,
      arguments: arguments,
      environment: environment
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      arguments,
      environment,
    ]
  }
  static func == (lhs: LaunchAppRequest, rhs: LaunchAppRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.appId, rhs.appId) && MessagesPigeonInternal.deepEquals(lhs.arguments, rhs.arguments) && MessagesPigeonInternal.deepEquals(lhs.environment, rhs.environment)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LaunchAppRequest")
    MessagesPigeonInternal.deepHash(value: appId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: arguments, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: environment, hasher: &hasher)
  }

  public var description: String {
    return "LaunchAppRequest(appId: \(String(describing: appId)), arguments: \(String(describing: arguments)), environment: \(String(describing: environment)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TapRequest: Hashable, CustomStringConvertible {
  var point: PointData
  var count: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TapRequest? {
    let point = pigeonVar_list[0] as! PointData
    let count = pigeonVar_list[1] as! Int64

    return TapRequest(
      point: point,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      point,
      count,
    ]
  }
  static func == (lhs: TapRequest, rhs: TapRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.point, rhs.point) && MessagesPigeonInternal.deepEquals(lhs.count, rhs.count)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TapRequest")
    MessagesPigeonInternal.deepHash(value: point, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: count, hasher: &hasher)
  }

  public var description: String {
    return "TapRequest(point: \(String(describing: point)), count: \(String(describing: count)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LongPressRequest: Hashable, CustomStringConvertible {
  var point: PointData
  var durationMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LongPressRequest? {
    let point = pigeonVar_list[0] as! PointData
    let durationMs = pigeonVar_list[1] as! Int64

    return LongPressRequest(
      point: point,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      point,
      durationMs,
    ]
  }
  static func == (lhs: LongPressRequest, rhs: LongPressRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.point, rhs.point) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LongPressRequest")
    MessagesPigeonInternal.deepHash(value: point, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
  }

  public var description: String {
    return "LongPressRequest(point: \(String(describing: point)), durationMs: \(String(describing: durationMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SwipeRequest: Hashable, CustomStringConvertible {
  var from: PointData
  var to: PointData
  var durationMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SwipeRequest? {
    let from = pigeonVar_list[0] as! PointData
    let to = pigeonVar_list[1] as! PointData
    let durationMs = pigeonVar_list[2] as! Int64

    return SwipeRequest(
      from: from,
      to: to,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      from,
      to,
      durationMs,
    ]
  }
  static func == (lhs: SwipeRequest, rhs: SwipeRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.from, rhs.from) && MessagesPigeonInternal.deepEquals(lhs.to, rhs.to) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SwipeRequest")
    MessagesPigeonInternal.deepHash(value: from, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: to, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
  }

  public var description: String {
    return "SwipeRequest(from: \(String(describing: from)), to: \(String(describing: to)), durationMs: \(String(describing: durationMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScrollRequest: Hashable, CustomStringConvertible {
  var deltaX: Double
  var deltaY: Double
  var origin: PointData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScrollRequest? {
    let deltaX = pigeonVar_list[0] as! Double
    let deltaY = pigeonVar_list[1] as! Double
    let origin: PointData? = nilOrValue(pigeonVar_list[2])

    return ScrollRequest(
      deltaX: deltaX,
      deltaY: deltaY,
      origin: origin
    )
  }
  func toList() -> [Any?] {
    return [
      deltaX,
      deltaY,
      origin,
    ]
  }
  static func == (lhs: ScrollRequest, rhs: ScrollRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.deltaX, rhs.deltaX) && MessagesPigeonInternal.deepEquals(lhs.deltaY, rhs.deltaY) && MessagesPigeonInternal.deepEquals(lhs.origin, rhs.origin)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScrollRequest")
    MessagesPigeonInternal.deepHash(value: deltaX, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deltaY, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: origin, hasher: &hasher)
  }

  public var description: String {
    return "ScrollRequest(deltaX: \(String(describing: deltaX)), deltaY: \(String(describing: deltaY)), origin: \(String(describing: origin)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TypeTextRequest: Hashable, CustomStringConvertible {
  var text: String
  var clearFirst: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TypeTextRequest? {
    let text = pigeonVar_list[0] as! String
    let clearFirst = pigeonVar_list[1] as! Bool

    return TypeTextRequest(
      text: text,
      clearFirst: clearFirst
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      clearFirst,
    ]
  }
  static func == (lhs: TypeTextRequest, rhs: TypeTextRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.clearFirst, rhs.clearFirst)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TypeTextRequest")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clearFirst, hasher: &hasher)
  }

  public var description: String {
    return "TypeTextRequest(text: \(String(describing: text)), clearFirst: \(String(describing: clearFirst)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KeyRequest: Hashable, CustomStringConvertible {
  var key: String
  var action: KeyAction
  var alt: Bool
  var control: Bool
  var shift: Bool
  var meta: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyRequest? {
    let key = pigeonVar_list[0] as! String
    let action = pigeonVar_list[1] as! KeyAction
    let alt = pigeonVar_list[2] as! Bool
    let control = pigeonVar_list[3] as! Bool
    let shift = pigeonVar_list[4] as! Bool
    let meta = pigeonVar_list[5] as! Bool

    return KeyRequest(
      key: key,
      action: action,
      alt: alt,
      control: control,
      shift: shift,
      meta: meta
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      action,
      alt,
      control,
      shift,
      meta,
    ]
  }
  static func == (lhs: KeyRequest, rhs: KeyRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.key, rhs.key) && MessagesPigeonInternal.deepEquals(lhs.action, rhs.action) && MessagesPigeonInternal.deepEquals(lhs.alt, rhs.alt) && MessagesPigeonInternal.deepEquals(lhs.control, rhs.control) && MessagesPigeonInternal.deepEquals(lhs.shift, rhs.shift) && MessagesPigeonInternal.deepEquals(lhs.meta, rhs.meta)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KeyRequest")
    MessagesPigeonInternal.deepHash(value: key, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: action, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: control, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shift, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: meta, hasher: &hasher)
  }

  public var description: String {
    return "KeyRequest(key: \(String(describing: key)), action: \(String(describing: action)), alt: \(String(describing: alt)), control: \(String(describing: control)), shift: \(String(describing: shift)), meta: \(String(describing: meta)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScreenshotRequest: Hashable, CustomStringConvertible {
  var targetId: String? = nil
  var format: ScreenshotFormat
  var quality: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScreenshotRequest? {
    let targetId: String? = nilOrValue(pigeonVar_list[0])
    let format = pigeonVar_list[1] as! ScreenshotFormat
    let quality = pigeonVar_list[2] as! Int64

    return ScreenshotRequest(
      targetId: targetId,
      format: format,
      quality: quality
    )
  }
  func toList() -> [Any?] {
    return [
      targetId,
      format,
      quality,
    ]
  }
  static func == (lhs: ScreenshotRequest, rhs: ScreenshotRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.targetId, rhs.targetId) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScreenshotRequest")
    MessagesPigeonInternal.deepHash(value: targetId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
  }

  public var description: String {
    return "ScreenshotRequest(targetId: \(String(describing: targetId)), format: \(String(describing: format)), quality: \(String(describing: quality)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScreenshotData: Hashable, CustomStringConvertible {
  var bytes: FlutterStandardTypedData
  var width: Int64
  var height: Int64
  var scale: Double
  var format: ScreenshotFormat


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScreenshotData? {
    let bytes = pigeonVar_list[0] as! FlutterStandardTypedData
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let scale = pigeonVar_list[3] as! Double
    let format = pigeonVar_list[4] as! ScreenshotFormat

    return ScreenshotData(
      bytes: bytes,
      width: width,
      height: height,
      scale: scale,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
      width,
      height,
      scale,
      format,
    ]
  }
  static func == (lhs: ScreenshotData, rhs: ScreenshotData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.scale, rhs.scale) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScreenshotData")
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
  }

  public var description: String {
    return "ScreenshotData(bytes: \(String(describing: bytes)), width: \(String(describing: width)), height: \(String(describing: height)), scale: \(String(describing: scale)), format: \(String(describing: format)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AutomationCapability(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AutomationPermission(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TargetType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UiRole(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UiAction(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SystemAction(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyAction(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScreenshotFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return PointData.fromList(self.readValue() as! [Any?])
    case 139:
      return RectData.fromList(self.readValue() as! [Any?])
    case 140:
      return SizeData.fromList(self.readValue() as! [Any?])
    case 141:
      return DriverConfig.fromList(self.readValue() as! [Any?])
    case 142:
      return DeviceInfo.fromList(self.readValue() as! [Any?])
    case 143:
      return ScreenInfo.fromList(self.readValue() as! [Any?])
    case 144:
      return CapabilityInfo.fromList(self.readValue() as! [Any?])
    case 145:
      return PermissionInfo.fromList(self.readValue() as! [Any?])
    case 146:
      return TargetInfo.fromList(self.readValue() as! [Any?])
    case 147:
      return UiNode.fromList(self.readValue() as! [Any?])
    case 148:
      return UiSnapshot.fromList(self.readValue() as! [Any?])
    case 149:
      return DumpUiRequest.fromList(self.readValue() as! [Any?])
    case 150:
      return HitTestRequest.fromList(self.readValue() as! [Any?])
    case 151:
      return ElementActionRequest.fromList(self.readValue() as! [Any?])
    case 152:
      return ActionResult.fromList(self.readValue() as! [Any?])
    case 153:
      return LaunchAppRequest.fromList(self.readValue() as! [Any?])
    case 154:
      return TapRequest.fromList(self.readValue() as! [Any?])
    case 155:
      return LongPressRequest.fromList(self.readValue() as! [Any?])
    case 156:
      return SwipeRequest.fromList(self.readValue() as! [Any?])
    case 157:
      return ScrollRequest.fromList(self.readValue() as! [Any?])
    case 158:
      return TypeTextRequest.fromList(self.readValue() as! [Any?])
    case 159:
      return KeyRequest.fromList(self.readValue() as! [Any?])
    case 160:
      return ScreenshotRequest.fromList(self.readValue() as! [Any?])
    case 161:
      return ScreenshotData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AutomationCapability {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AutomationPermission {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? TargetType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? UiRole {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? UiAction {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? SystemAction {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeyAction {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScreenshotFormat {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? PointData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? RectData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? SizeData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? DriverConfig {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceInfo {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? ScreenInfo {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? CapabilityInfo {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? PermissionInfo {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? TargetInfo {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? UiNode {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? UiSnapshot {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? DumpUiRequest {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? HitTestRequest {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? ElementActionRequest {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? ActionResult {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? LaunchAppRequest {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? TapRequest {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? LongPressRequest {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? SwipeRequest {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? ScrollRequest {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? TypeTextRequest {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? KeyRequest {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? ScreenshotRequest {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? ScreenshotData {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AutomationHostApi {
  func initialize(config: DriverConfig) throws
  func shutdown() throws
  func getDeviceInfo() throws -> DeviceInfo
  func getScreenInfo() throws -> ScreenInfo
  func getCapabilities() throws -> CapabilityInfo
  func getPermissions() throws -> [PermissionInfo?]
  func requestPermission(permission: AutomationPermission) throws -> PermissionInfo
  func listTargets() throws -> [TargetInfo?]
  func getForegroundTarget() throws -> TargetInfo?
  func launchApp(request: LaunchAppRequest) throws -> ActionResult
  func terminateApp(appId: String) throws -> ActionResult
  func activateTarget(targetId: String) throws -> ActionResult
  func dumpUi(request: DumpUiRequest) throws -> UiSnapshot
  func hitTest(request: HitTestRequest) throws -> UiNode?
  func performElementAction(request: ElementActionRequest) throws -> ActionResult
  func tap(request: TapRequest) throws -> ActionResult
  func longPress(request: LongPressRequest) throws -> ActionResult
  func swipe(request: SwipeRequest) throws -> ActionResult
  func scroll(request: ScrollRequest) throws -> ActionResult
  func typeText(request: TypeTextRequest) throws -> ActionResult
  func pressKey(request: KeyRequest) throws -> ActionResult
  func performSystemAction(action: SystemAction) throws -> ActionResult
  func screenshot(request: ScreenshotRequest) throws -> ScreenshotData
  func getClipboardText() throws -> String?
  func setClipboardText(text: String) throws -> ActionResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AutomationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AutomationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AutomationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! DriverConfig
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let shutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.shutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shutdownChannel.setMessageHandler { _, reply in
        do {
          try api.shutdown()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      shutdownChannel.setMessageHandler(nil)
    }
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
    let getScreenInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getScreenInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScreenInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getScreenInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScreenInfoChannel.setMessageHandler(nil)
    }
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let getPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPermissionsChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! AutomationPermission
        do {
          let result = try api.requestPermission(permission: permissionArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let listTargetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.listTargets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listTargetsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listTargets()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listTargetsChannel.setMessageHandler(nil)
    }
    let getForegroundTargetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getForegroundTarget\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getForegroundTargetChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getForegroundTarget()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getForegroundTargetChannel.setMessageHandler(nil)
    }
    let launchAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.launchApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchAppChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LaunchAppRequest
        do {
          let result = try api.launchApp(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      launchAppChannel.setMessageHandler(nil)
    }
    let terminateAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.terminateApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      terminateAppChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        do {
          let result = try api.terminateApp(appId: appIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      terminateAppChannel.setMessageHandler(nil)
    }
    let activateTargetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.activateTarget\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activateTargetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let targetIdArg = args[0] as! String
        do {
          let result = try api.activateTarget(targetId: targetIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activateTargetChannel.setMessageHandler(nil)
    }
    let dumpUiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.dumpUi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dumpUiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DumpUiRequest
        do {
          let result = try api.dumpUi(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      dumpUiChannel.setMessageHandler(nil)
    }
    let hitTestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.hitTest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hitTestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HitTestRequest
        do {
          let result = try api.hitTest(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hitTestChannel.setMessageHandler(nil)
    }
    let performElementActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.performElementAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      performElementActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ElementActionRequest
        do {
          let result = try api.performElementAction(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      performElementActionChannel.setMessageHandler(nil)
    }
    let tapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.tap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      tapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TapRequest
        do {
          let result = try api.tap(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      tapChannel.setMessageHandler(nil)
    }
    let longPressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.longPress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      longPressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LongPressRequest
        do {
          let result = try api.longPress(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      longPressChannel.setMessageHandler(nil)
    }
    let swipeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.swipe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      swipeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SwipeRequest
        do {
          let result = try api.swipe(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      swipeChannel.setMessageHandler(nil)
    }
    let scrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.scroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ScrollRequest
        do {
          let result = try api.scroll(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      scrollChannel.setMessageHandler(nil)
    }
    let typeTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.typeText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      typeTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TypeTextRequest
        do {
          let result = try api.typeText(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      typeTextChannel.setMessageHandler(nil)
    }
    let pressKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.pressKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pressKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! KeyRequest
        do {
          let result = try api.pressKey(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pressKeyChannel.setMessageHandler(nil)
    }
    let performSystemActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.performSystemAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      performSystemActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let actionArg = args[0] as! SystemAction
        do {
          let result = try api.performSystemAction(action: actionArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      performSystemActionChannel.setMessageHandler(nil)
    }
    let screenshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.screenshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      screenshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ScreenshotRequest
        do {
          let result = try api.screenshot(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      screenshotChannel.setMessageHandler(nil)
    }
    let getClipboardTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.getClipboardText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getClipboardTextChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getClipboardText()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getClipboardTextChannel.setMessageHandler(nil)
    }
    let setClipboardTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.device_kit_lib.AutomationHostApi.setClipboardText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setClipboardTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          let result = try api.setClipboardText(text: textArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setClipboardTextChannel.setMessageHandler(nil)
    }
  }
}
