// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum UiAction {
  press,
  focus,
  setValue,
  scrollForward,
  scrollBackward,
}

class DriverConfig {
  DriverConfig({
    required this.sessionId,
    required this.enableLogs,
  });

  String sessionId;

  bool enableLogs;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      enableLogs,
    ];
  }

  Object encode() {
    return _toList();  }

  static DriverConfig decode(Object result) {
    result as List<Object?>;
    return DriverConfig(
      sessionId: result[0]! as String,
      enableLogs: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DriverConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(enableLogs, other.enableLogs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DriverConfig(sessionId: $sessionId, enableLogs: $enableLogs)';
  }
}

class DeviceInfo {
  DeviceInfo({
    required this.platform,
    this.osVersion,
    this.model,
    this.deviceName,
    required this.physicalDevice,
  });

  String platform;

  String? osVersion;

  String? model;

  String? deviceName;

  bool physicalDevice;

  List<Object?> _toList() {
    return <Object?>[
      platform,
      osVersion,
      model,
      deviceName,
      physicalDevice,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceInfo decode(Object result) {
    result as List<Object?>;
    return DeviceInfo(
      platform: result[0]! as String,
      osVersion: result[1] as String?,
      model: result[2] as String?,
      deviceName: result[3] as String?,
      physicalDevice: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platform, other.platform) && _deepEquals(osVersion, other.osVersion) && _deepEquals(model, other.model) && _deepEquals(deviceName, other.deviceName) && _deepEquals(physicalDevice, other.physicalDevice);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceInfo(platform: $platform, osVersion: $osVersion, model: $model, deviceName: $deviceName, physicalDevice: $physicalDevice)';
  }
}

class RectData {
  RectData({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static RectData decode(Object result) {
    result as List<Object?>;
    return RectData(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RectData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RectData(x: $x, y: $y, width: $width, height: $height)';
  }
}

class UiNode {
  UiNode({
    required this.nodeId,
    this.parentNodeId,
    required this.childNodeIds,
    this.automationId,
    this.text,
    this.label,
    this.value,
    required this.role,
    required this.bounds,
    required this.enabled,
    required this.clickable,
    required this.editable,
    required this.focused,
    required this.selected,
    required this.checked,
    required this.scrollable,
  });

  String nodeId;

  String? parentNodeId;

  List<String> childNodeIds;

  String? automationId;

  String? text;

  String? label;

  String? value;

  String role;

  RectData bounds;

  bool enabled;

  bool clickable;

  bool editable;

  bool focused;

  bool selected;

  bool checked;

  bool scrollable;

  List<Object?> _toList() {
    return <Object?>[
      nodeId,
      parentNodeId,
      childNodeIds,
      automationId,
      text,
      label,
      value,
      role,
      bounds,
      enabled,
      clickable,
      editable,
      focused,
      selected,
      checked,
      scrollable,
    ];
  }

  Object encode() {
    return _toList();  }

  static UiNode decode(Object result) {
    result as List<Object?>;
    return UiNode(
      nodeId: result[0]! as String,
      parentNodeId: result[1] as String?,
      childNodeIds: (result[2]! as List<Object?>).cast<String>(),
      automationId: result[3] as String?,
      text: result[4] as String?,
      label: result[5] as String?,
      value: result[6] as String?,
      role: result[7]! as String,
      bounds: result[8]! as RectData,
      enabled: result[9]! as bool,
      clickable: result[10]! as bool,
      editable: result[11]! as bool,
      focused: result[12]! as bool,
      selected: result[13]! as bool,
      checked: result[14]! as bool,
      scrollable: result[15]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UiNode || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(nodeId, other.nodeId) && _deepEquals(parentNodeId, other.parentNodeId) && _deepEquals(childNodeIds, other.childNodeIds) && _deepEquals(automationId, other.automationId) && _deepEquals(text, other.text) && _deepEquals(label, other.label) && _deepEquals(value, other.value) && _deepEquals(role, other.role) && _deepEquals(bounds, other.bounds) && _deepEquals(enabled, other.enabled) && _deepEquals(clickable, other.clickable) && _deepEquals(editable, other.editable) && _deepEquals(focused, other.focused) && _deepEquals(selected, other.selected) && _deepEquals(checked, other.checked) && _deepEquals(scrollable, other.scrollable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UiNode(nodeId: $nodeId, parentNodeId: $parentNodeId, childNodeIds: $childNodeIds, automationId: $automationId, text: $text, label: $label, value: $value, role: $role, bounds: $bounds, enabled: $enabled, clickable: $clickable, editable: $editable, focused: $focused, selected: $selected, checked: $checked, scrollable: $scrollable)';
  }
}

class UiSnapshot {
  UiSnapshot({
    required this.generation,
    required this.nodes,
  });

  int generation;

  List<UiNode> nodes;

  List<Object?> _toList() {
    return <Object?>[
      generation,
      nodes,
    ];
  }

  Object encode() {
    return _toList();  }

  static UiSnapshot decode(Object result) {
    result as List<Object?>;
    return UiSnapshot(
      generation: result[0]! as int,
      nodes: (result[1]! as List<Object?>).cast<UiNode>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UiSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(generation, other.generation) && _deepEquals(nodes, other.nodes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UiSnapshot(generation: $generation, nodes: $nodes)';
  }
}

class ActionResult {
  ActionResult({
    required this.success,
    this.message,
    required this.uiChanged,
  });

  bool success;

  String? message;

  bool uiChanged;

  List<Object?> _toList() {
    return <Object?>[
      success,
      message,
      uiChanged,
    ];
  }

  Object encode() {
    return _toList();  }

  static ActionResult decode(Object result) {
    result as List<Object?>;
    return ActionResult(
      success: result[0]! as bool,
      message: result[1] as String?,
      uiChanged: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ActionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(message, other.message) && _deepEquals(uiChanged, other.uiChanged);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ActionResult(success: $success, message: $message, uiChanged: $uiChanged)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is UiAction) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DriverConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is RectData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is UiNode) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is UiSnapshot) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ActionResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : UiAction.values[value];
      case 130:
        return DriverConfig.decode(readValue(buffer)!);
      case 131:
        return DeviceInfo.decode(readValue(buffer)!);
      case 132:
        return RectData.decode(readValue(buffer)!);
      case 133:
        return UiNode.decode(readValue(buffer)!);
      case 134:
        return UiSnapshot.decode(readValue(buffer)!);
      case 135:
        return ActionResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DeviceKitHostApi {
  /// Constructor for [DeviceKitHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceKitHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(DriverConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<DeviceInfo> getDeviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeviceInfo;
  }

  Future<ActionResult> openAccessibilitySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.openAccessibilitySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> launchApp(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.launchApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<UiSnapshot> dumpUi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.dumpUi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as UiSnapshot;
  }

  Future<ActionResult> performElementAction(String nodeId, int generation, UiAction action, String? value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.performElementAction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[nodeId, generation, action, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> tap(double x, double y) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.tap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[x, y]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> swipe(double fromX, double fromY, double toX, double toY, int durationMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.swipe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fromX, fromY, toX, toY, durationMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> typeText(String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.typeText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> pressBack() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressBack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<ActionResult> pressHome() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.pressHome$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<Uint8List> screenshot() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.screenshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<ActionResult> requestScreenCapture() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.requestScreenCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }

  Future<String?> getClipboard() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.getClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<ActionResult> setClipboard(String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.device_kit_lib.DeviceKitHostApi.setClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ActionResult;
  }
}
